### Signup 201 Success
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "StrongPassword123!",
  "requires2FA": true
}

### Signup 409 Conflict - Email already exists
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "StrongPassword123!",
  "requires2FA": true
}

### Signup 422 Unprocessable Entity - Missing email
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "password": "password123",
  "requires2FA": true
}

### Signup 422 Unprocessable Entity - Missing password
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "requires2FA": true
}

### Signup 422 Unprocessable Entity - Missing requires2FA
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123"
}

### Signup 422 Unprocessable Entity - Empty JSON Object
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{}

### Signup 400 Bad Request - Empty Payload
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

### Signup 422 Unprocessable Entity - Invalid JSON Literal Payload
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

1

### Signup 400 Bad Request - Invalid JSON Literal
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123",
  "requires2FA": truth
}

### Signup 422 Unprocessable Entity - Invalid Boolean Literal
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "password123",
  "requires2FA": 1
}

### Signup 422 Unprocessable Entity - Null Values
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": null,
  "password": null,
  "requires2FA": false
}

### Signup 400 Bad Request - Empty Strings
POST http://{{hostname}}:{{port}}/api/signup
Content-Type: application/json

{
  "email": "",
  "password": "",
  "requires2FA": false
}
