name: Build, Test and Deploy to Prod

# Trigger the workflow when changes are pushed to the main branch
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{ vars.POSTGRES_DB }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
        ports:
          - ${{ vars.POSTGRES_PORT }}:5432
      cache:
        image: redis:latest
        ports:
          - ${{ vars.REDIS_PORT }}:6379

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

        # Cache dependencies to speed up build times
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            app-service/.cargo
            app-service/target/
            auth-service/.cargo
            auth-service/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Build and test app-service code
        working-directory: ./app-service
        run: |
          cargo build --verbose
          cargo test --verbose

      - name: Build and test auth-service code
        working-directory: ./auth-service
        run: |
          export AUTH_SERVICE_CACHE_ENGINE=redis
          export AUTH_SERVICE_CACHE_HOST=cache
          export AUTH_SERVICE_CACHE_PORT=6379
          export AUTH_SERVICE_DB_ENGINE=postgres
          export AUTH_SERVICE_DB_HOST=db
          export AUTH_SERVICE_DB_NAME=${{ vars.POSTGRES_DB }}
          export AUTH_SERVICE_DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          export AUTH_SERVICE_DB_POOL_MAX=${{ vars.POSTGRES_POOL_MAX }}
          export AUTH_SERVICE_DB_POOL_MIN=${{ vars.POSTGRES_POOL_MIN }}
          export AUTH_SERVICE_DB_PORT=5432
          export AUTH_SERVICE_DB_USER=${{ secrets.POSTGRES_USER }}
          export AUTH_SERVICE_EMAIL_SERVICE=postmark
          export AUTH_SERVICE_EMAIL_API_KEY=${{ secrets.POSTMARK_AUTH_TOKEN }}
          export AUTH_SERVICE_EMAIL_API_TIMEOUT=${{ vars.POSTMARK_TIMEOUT }}
          export AUTH_SERVICE_EMAIL_API_URL=${{ vars.POSTMARK_API_URL }}
          export AUTH_SERVICE_EMAIL_SENDER=${{ vars.POSTMARK_SENDER }}
          export AUTH_SERVICE_EMAIL_STREAM=${{ vars.POSTMARK_STREAM }}
          export AUTH_SERVICE_JWT_SECRET=${{ secrets.AUTH_SERVICE_JWT_SECRET }}
          export AUTH_SERVICE_JWT_TTL=${{ vars.AUTH_SERVICE_JWT_TTL }}
          export AUTH_SERVICE_LOG_LEVEL=trace
          export APP_SERVICE_PORT=8000
          export AUTH_SERVICE_HOST_IPV4=127.0.0.1
          export AUTH_SERVICE_PORT=3000
          export AUTH_SERVICE_TFA_TTL=${{ vars.AUTH_SERVICE_TFA_TTL }}
          export DATABASE_URL=postgresql://${{ secrets.POSTGRES_USER }}:${{ secrets.POSTGRES_PASSWORD }}@db:5432/${{ vars.POSTGRES_DB }}
          export SQLX_OFFLINE=true
          cargo build --verbose
          cargo test --verbose

        # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/bake-action@v2.3.0
        with:
          push: true
          files: |
            compose.yml
            compose.override.yml
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Install sshpass
        run: sudo apt-get install sshpass

      - name: Copy compose.yml to droplet
        run: sshpass -v -p '${{ secrets.DROPLET_PASSWORD }}' scp -o StrictHostKeyChecking=no compose.yml root@${{ vars.DROPLET_IP }}:~

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.DROPLET_IP }}
          username: root
          password: ${{ secrets.DROPLET_PASSWORD }}
          script: |
            cd ~
            export AUTH_SERVICE_CACHE_ENGINE=redis
            export AUTH_SERVICE_CACHE_HOST=cache
            export AUTH_SERVICE_CACHE_PORT=6379
            export AUTH_SERVICE_DB_ENGINE=postgres
            export AUTH_SERVICE_DB_HOST=db
            export AUTH_SERVICE_DB_NAME=${{ vars.POSTGRES_DB }}
            export AUTH_SERVICE_DB_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export AUTH_SERVICE_DB_POOL_MAX=${{ vars.POSTGRES_POOL_MAX }}
            export AUTH_SERVICE_DB_POOL_MIN=${{ vars.POSTGRES_POOL_MIN }}
            export AUTH_SERVICE_DB_PORT=5432
            export AUTH_SERVICE_DB_USER=${{ secrets.POSTGRES_USER }}
            export AUTH_SERVICE_EMAIL_SERVICE=postmark
            export AUTH_SERVICE_EMAIL_API_KEY=${{ secrets.POSTMARK_AUTH_TOKEN }}
            export AUTH_SERVICE_EMAIL_API_TIMEOUT=${{ vars.POSTMARK_TIMEOUT }}
            export AUTH_SERVICE_EMAIL_API_URL=${{ vars.POSTMARK_API_URL }}
            export AUTH_SERVICE_EMAIL_SENDER=${{ vars.POSTMARK_SENDER }}
            export AUTH_SERVICE_EMAIL_STREAM=${{ vars.POSTMARK_STREAM }}
            export AUTH_SERVICE_JWT_SECRET=${{ secrets.AUTH_SERVICE_JWT_SECRET }}
            export AUTH_SERVICE_JWT_TTL=${{ vars.AUTH_SERVICE_JWT_TTL }}
            export AUTH_SERVICE_LOG_LEVEL=trace
            export APP_SERVICE_PORT=8000
            export AUTH_SERVICE_HOST_IPV4=${{ vars.DROPLET_IP }}
            export AUTH_SERVICE_PORT=3000
            export AUTH_SERVICE_TFA_TTL=${{ vars.AUTH_SERVICE_TFA_TTL }}
            docker compose down
            docker compose pull
            docker compose up -d